### ISSUE TITLE
Eliminate all compiler warnings.

### ISSUE THREAD

**Issue by heinsaar** [heinsaar/BolzmANN#5]

**Comment by NorayrAvetisyan** [comment]
Warning	LNK4075	ignoring '/INCREMENTAL' due to '/PROFILE' specification	ANN	C:\Users\Norayr\Documents\GitHub\ANN\ANN\LINK

Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification	ANN	C:\Users\Norayr\Documents\GitHub\ANN\ANN\main.obj	1

These two warnings are not related to code.

**Comment by heinsaar** [comment]
We'll have to try to eliminate these too.
